version: '2.1'
orbs:
  node: circleci/node@x.y
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
workflows:
  test:
    jobs:
      - node/test:
          test-results-for: jest
  run-npm-command:
    jobs:
      - node/run:
          npm-run: build
  test-and-deploy:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - master
          requires:
            - node/test          
    
