version: '2.1'
orbs:
  node: circleci/node@5.1.0
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: cd server && npm install && npm test
workflows:
  test:
    jobs:
      - node/test:
          test-results-for: jest
  run-npm-command:
    jobs:
      - node/run:
          npm-run: build       
    
